### PR TITLE
WCAG 2.2 Accessibility updates.

### PR DESCRIPTION
**Pull request by jamiegood**
hello, 

a couple of small accessibility updates

See issue https://github.com/knocklabs/javascript/issues/182

Thanks

### CODE REVIEW

**Comment by connorlindsey** [comment]
Hey @jamiegood, thanks for the PR but sorry for the slow review, I'll take a look soon

**Comment by connorlindsey** [comment]
@jamiegood these changes look great. To get this merged, could you do the following:
- Run `yarn format` from the project root to ensure it passes CI
- Run `yarn changeset` to create a patch changeset for `@knocklabs/react` with the message "fix: add label to notification filter select"

I don't have access to your fork, otherwise I would go ahead and do these. Once that's done, we can get this merged, thanks!

**Comment by jamiegood** [comment]
Hi @connorlindsey 

Sure thing. How does this look?

Thanks

**Comment by connorlindsey** [comment]
@jamiegood This is perfect, thanks for your contribution!

**Pull request merged**
